#!/bin/sh
set -e

ZIG_BIN="/usr/lib/zig/ZIG_VERSION/zig"

if [ -x "$ZIG_BIN" ]; then
    update-alternatives --install /usr/bin/zig zig "$ZIG_BIN" 100
fi

ZLS_BIN="/usr/lib/zig/ZIG_VERSION/zls"

if [ -x "$ZLS_BIN" ]; then
    update-alternatives --install /usr/bin/zls zls "$ZLS_BIN" 100
fi

exit 0

