name: Build zig master for Debian

on:
  workflow_dispatch:
    inputs:
      zig_version:
        description: The version of zig to build.
        type: string
        required: true
      build_version:
        description: The build version.
        type: string
        required: true

permissions:
  contents: write

jobs:
  build-zig:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout zig-debian
        uses: actions/checkout@v4

      - name: Build zig
        run: ./build_zig_debian.sh ${{ inputs.zig_version }} ${{ inputs.build_version }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: zig-master_*.deb


  release-zig:
    name: (Draft-)Release zig for Debian
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-zig
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Publish Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: zig-master_*.deb
          name: ${{ inputs.zig_version }}+${{ inputs.build_version }}
          tag_name: ${{ env.RELEASE_TAG }}
          fail_on_unmatched_files: true

